version: '3.9'

services:
  api:
    container_name: softclinic-back
    build: ./soft-clinic-back
    ports:
      - '3000:3000'
    depends_on:
      - mysql
      - minio
    env_file:
      - .env
    volumes:
      - ./soft-clinic-back:/usr/src/app
    networks:
      - softclinic

  mysql:
    image: mysql:8
    container_name: softclinic-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: softclinic
      MYSQL_USER: clinic_user
      MYSQL_PASSWORD: clinic_pass
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - softclinic

  minio:
    image: minio/minio
    container_name: softclinic-minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    volumes:
      - minio_data:/data
    networks:
      - softclinic

volumes:
  mysql_data:
  minio_data:

networks:
  softclinic:
