# Dockerfile.dev
FROM node:22-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

# Instala o Nest CLI globalmente para usar `nest start`
RUN npm install -g @nestjs/cli

CMD ["sh", "-c", "npm run migration:run && ts-node src/seeds/seed-permissions-roles.ts && npm run start:dev"]
