version: '3.9'

services:
  nest:
    container_name: soft-clinic-nest
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    env_file:
      - .env.development
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev
    depends_on:
      - mysql
      - minio
    networks:
      - soft-clinic-network

  mysql:
    image: mysql:8
    container_name: soft-clinic-mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: softclinic
      MYSQL_USER: clinic_user
      MYSQL_PASSWORD: clinic_pass
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - soft-clinic-network

  minio:
    image: minio/minio
    container_name: soft-clinic-minio
    command: server /data --console-address ":9001"
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    volumes:
      - minio_data:/data
    networks:
      - soft-clinic-network

volumes:
  mysql_data:
  minio_data:

networks:
  soft-clinic-network:
    name: soft-clinic-network