# Dockerfile.dev
FROM node:22-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

# Instala o Nest CLI globalmente para usar `nest start`
RUN npm install -g @nestjs/cli

CMD ["npm", "run", "start:dev"]
